//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopeeAutomationUserInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeBuyer
    {
        public int buyer_id { get; set; }
        public string buyer_username { get; set; }
        public string buyer_name { get; set; }
        public string buyer_mobile_phone { get; set; }
    }
}
