//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopeeAutomationUserInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeOrder
    {
        public string order_id { get; set; }
        public string refund_status { get; set; }
        public string voucher_code { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> purchase_date_time { get; set; }
        public Nullable<decimal> extra_charges { get; set; }
        public Nullable<decimal> order_income { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public Nullable<int> shipping_detail_id { get; set; }
        public Nullable<int> order_transaction_id { get; set; }
    }
}
